Victor-IX/Blender-Launcher-V2

- pyproject.toml
- source/items/base_list_widget_item.py
- source/main.py
- source/modules/_copyfileobj.py
- source/modules/_platform.py
- source/modules/build_info.py
- source/modules/connection_manager.py
- source/modules/settings.py
- source/modules/shortcut.py
- source/threads/folder_observer.py
- source/threads/library_drawer.py
- source/threads/scraper.py
- source/threads/template_installer.py
- source/widgets/base_line_edit.py
- source/widgets/base_list_widget.py
- source/widgets/base_menu_widget.py
- source/widgets/download_widget.py
- source/widgets/elided_text_label.py
- source/widgets/left_icon_button_widget.py
- source/widgets/library_widget.py
- source/widgets/settings_window/connection_tab.py
- source/widgets/settings_window/general_tab.py
- source/windows/dialog_window.py
- source/windows/file_dialog_window.py
- source/windows/main_window.py
- source/windows/settings_window.py
- source/windows/update_window.py
This resolves all the other ruff issues that were left from the Ruff rules pr. These rules were not automatically fixable.
> manual ruff fixes

- .gitignore
- source/widgets/settings_window/general_tab.py
- source/windows/file_dialog_window.py
- source/windows/main_window.py
- This fixes #30
- getExistingDirectory is a static method on the parent class
- Better to differentiate as a unique method of only the child class
> 🐞 Fix recursive import of static method

- source/items/base_list_widget_item.py
- source/widgets/base_list_widget.py
- source/widgets/download_widget.py
- source/widgets/library_widget.py
- source/windows/main_window.py
The first thing I've been meaning to get around to, the second thing was suggested by @willgfx on discord
https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/c331c15e-16e0-4bf6-88c5-14f8bc354224
> Click installed builds to focus it in the library, shared context menu between installed builds and library builds

- source/widgets/library_widget.py
- source/windows/main_window.py
I will upload a video of it in action later today.
> Allow editing ordinary builds in the library

- source/main.py
- source/modules/_platform.py
- source/modules/argument_parsing.py
- source/threads/scraper.py
- source/windows/dialog_window.py
- source/windows/main_window.py
- source/windows/update_window.py
Using argparse allows for a more intuitive commandline experience, especially for when launching files from the commandline gets supported
> Use argparse for parsing commandline arguments

- source/main.py
- source/modules/_platform.py
- source/modules/settings.py
- source/windows/main_window.py
Configuration and log files should be stored in the XDG Base Directory.
- windows
- Blender Laucnher.ini --> `%LOCALAPPDATA%/Blender Launcher/Blender Launcher.ini`
- Blender Launcher.log -->`%LOCALAPPDATA%/Blender Launcher/Blender Launcher.log` 
- mac / linux
- Blender Laucnher.ini --> `$XDG_CONFIG_HOME/Blender Launcher/Blender Launcher.ini`
- Blender Launcher.log -->`$XDG_CACHE_HOME/Blender Launcher/Blender Launcher.log`
> Support XDG_CONFIG_PATH/XDG_CACHE_PATH

- source/main.py
- source/modules/settings.py
- source/threads/scraper.py
- source/widgets/settings_window/general_tab.py
- source/windows/main_window.py
This adds the option to use pre-release builds instead of stable builds
Don't hesitate to give me feedback on what I made, there is probably some way to make it cleaner
Stuff I need to fix:
- Switching to pre-release and going back to stable without updating the version is currently not clearing the update button
> Add the option to use pre-release build

- docs/mkdocs/installation.md
- extras/blenderlauncher.desktop
- zip_linux.sh
this is the revision of my #99
> add archlinux installation extras

- source/modules/settings.py
- source/threads/scraper.py
- source/widgets/settings_window/blender_builds_tab.py
Changing the manual version input to a version dropdown to make it easier to change the minimum version
> Adding a Dropdown menu to select the minimum blender version

- source/modules/settings.py
- source/threads/scraper.py
- source/widgets/settings_window/blender_builds_tab.py
Add the option to scrap archive builds from the different archive JSON API files
> Add option to scrap archive builds

- docs/mkdocs/settings.md
- source/modules/settings.py
- source/widgets/settings_window/appearance_tab.py
- source/widgets/settings_window/blender_builds_tab.py
- source/widgets/settings_window/connection_tab.py
- source/widgets/settings_window/general_tab.py
Add tooltips on all the settings.  
The general tab will be done when the preference manager is done, as the tab has been reworked in this branch, and I want to prevent potential conflicts.
> Settings Tooltips

- source/widgets/settings_window/general_tab.py
Move the General Tab Rework to a separate PR to prevent future conflict and make the preference manager PR more readable
@zeptofine you can merge it if everything is good on your side
> Settings General Tab Rework

- pdm.lock
- pyproject.toml
- source/threads/remover.py
- source/widgets/base_menu_widget.py
- source/widgets/library_widget.py
This adds an option to send files to trash using `send2trash`. 
Shift-right clicking keeps the original usage.
> Allow sending files to trash instead of deleting

- pdm.lock
- pyproject.toml
- source/modules/_platform.py
- source/modules/build_info.py
- source/threads/scraper.py
This uses the `dateparser` package to simplify working with datetimes regarding locales, and lets the GUI use locale specific dates in the downloader
> add dateparser functionality

- pyproject.toml
- source/modules/settings.py
- source/threads/extractor.py
- source/threads/library_drawer.py
- source/threads/scraper.py
- source/widgets/base_build_widget.py
- source/widgets/download_widget.py
- source/widgets/library_widget.py
- source/windows/main_window.py
[Bforartists](https://www.bforartists.de/) is one of the few major Blender forks out there, it has been around for more than 8 years and maintained its own user base,
this PR was sponsored by @Draise14 to support listing, downloading and launching of Bforartists releases,
the original idea was to fork it as its own launcher,
but personally I immediately saw, even before starting working on it, that it is more suitable to merge it into the main project, since the change is very small anyways,
and this PR indeed reflects that, the changes are minimal and don't affect the Blender side of the code.
> Support the major Blender fork Bforartists

- source/modules/_platform.py
- source/modules/build_info.py
- source/resources/api/blender_launcher_api.json
- source/widgets/library_widget.py
Add a new button in the Right-click menu to open the Blender Config folder
#146
> Add new Button to open build config folder

- source/modules/settings.py
- source/widgets/library_widget.py
- source/widgets/settings_window/general_tab.py
Add the option to flip the default behaviour of the delete build option 
Feat [#156](https://github.com/Victor-IX/Blender-Launcher-V2/issues/156)
> Delete build option

- source/widgets/library_widget.py
Add the option to open the portable config folder with shift support to open the global settings folder instead
#179
> Add the option to open the portable config folder

- source/modules/cli_launching.py
Resolves issue described in #243.
> launch cli - handle error if there are no builds for the specified query #243

- source/modules/_platform.py
> Fix error displaying launch --help for Windows executable

- docs/mkdocs/index.md
Fixed a typo and updated the major feature list
> Update index.md in docs
