source/threads/scraper.py, source/widgets/download_widget.py
This replaces the beautifulsoup scraping method for experimental / daily / patch builds with the much simpler JSON api they provide
I also added a print statement if no releases could be found from `stable`
This also opens up the possibility of using the json data for labels and such!
as for the download_widget, I'm not so sure if the decision it makes there should even *be* there... I feel it should also be created during build_info generation instead
=> Use blender's JSON api for builds available from builder.blender.org

source/threads/scraper.py, source/widgets/download_widget.py
This adds branch names to the experimental builds, and shows daily variants too i think
fixes #23
=> Experimental patch names

source/widgets/library_widget.py
If a list widget is somehow replaced, like custom user builds, the builds that are marked as favorites are duplicated. this checks if the build_info exists in the favorites list before attempting to add the item to the list.
=> fix favorite duplication

.github/workflows/release.yml, pyproject.toml
To fix #15 on Ubuntu systems, I made an automated github action that automatically build the app on version release.
For example: https://github.com/RustyNova016/Blender-Launcher-V2/releases/tag/v1.16.1
=> Github action for automated Ubuntu builds

source/modules/build_info.py, source/modules/task.py, source/modules/tasks.py, source/threads/downloader.py, source/threads/extractor.py, source/threads/library_drawer.py, source/threads/remover.py, source/threads/renamer.py, source/threads/scraper.py, source/threads/template_installer.py, source/widgets/download_widget.py, source/widgets/library_widget.py, source/windows/custom_build_dialog_window.py, source/windows/main_window.py, source/windows/update_window.py
QT already has QActions, and I forgot about them as I was creating the Actions and the Action queue
I made this pr because It feels like confusion will arise from having two things having the same name and doing very different things
This isn't a very important change as it's simply a renaming, so if we want to just ditch this it's fine imo
=> Rename actions to tasks

source/modules/icons.py, source/widgets/library_widget.py
Related to #58 and #60
0:00 launching normally
0:12 Saving project
0:19 launching normally again
0:28 while holding alt, launching with the last file loaded
https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/b8a45032-b1a2-4c33-ba0e-e43139c684a7
=> add shortcut to --use-last by holding shift while triggering a launch

source/modules/settings.py, source/widgets/settings_window/general_tab.py, source/windows/base_window.py, source/windows/main_window.py, source/windows/settings_window.py
Making windows frameless have been creating a few issues on some Linux distributions. This allows users to disable the custom title bar if they feel like using the system default one is easier.
related to #52
https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/af02f1b9-17d8-4f79-ba0b-4f869fcc300e
=> add option to use system title bar

source/modules/settings.py, source/threads/scraper.py, source/widgets/settings_window/blender_builds_tab.py, source/windows/main_window.py
For some of us, it is a waste of time / bandwidth to scrape the stable builds because they usually use the daily/experimental builds, and on the flipside, some never intend to use the daily/experimental builds. These two options allow someone to just skip the different methods.
=> Add checkboxes to scrape only stable or automated builds

source/main.py, source/modules/_platform.py, source/modules/settings.py, source/widgets/settings_window/general_tab.py, source/windows/main_window.py
This is sort of an extension to #88 that moved the config to the user settings. This was good, however it removed the ability for the application to be fully portable as the settings were bound to the user's account. This adds a button in the settings to migrate the file instead of the program doing so automatically
=> Make migrating settings to user config optional

source/modules/_platform.py, source/modules/build_info.py, source/modules/scraper_cache.py, source/modules/settings.py, source/threads/scraper.py
This extends caching the versions to a local file.
This reduces the number of requests made to the Blender foundation and makes subsequent requests faster
=> cache stable builds to local file

source/modules/settings.py, source/windows/main_window.py
Something I've noticed for a lot of people running it for a first time is they don't know about the system tray icon and understandably expects it to fully close when they close the window. What this does is make a message pop up the first time they close the app if they have tray icons enabled to make sure they actually know this is a feature
=> Add a message to notify the existence of tray icon feature

scripts/build_linux.sh
get this error when building the package on linux
```
Using Python interpreter: /run/media/officestorage/karya/contrib/AUR/blender-launcher-git/src/Blender-Launcher-V2/lib/bin/python (3.9)
source /run/media/officestorage/karya/contrib/AUR/blender-launcher-git/src/Blender-Launcher-V2/lib/bin/activate
WARNING: Lockfile hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
🔒 Lock successful
Changes are written to pdm.lock.
All packages are synced to date, nothing to do.
Installing the project as an editable package...
✔ Update blender-launcher-v2 2.1.24 -> 2.1.24 successful
🎉 All complete!
build_linux.sh: line 1: cd..: command not found
build_linux.sh: line 2: pyinstaller: command not found
==> ERROR: A failure occurred in build().
Aborting...
```
it's typo on …
=> fix build error for linux

source/modules/_platform.py, source/threads/scraper.py
This adds an architecture notification to the branch string in certain builds, in the same style that MacOS builds are displayed.
Would we want to add an architecture value to build infos?
=> Add architecture displays to builds

source/widgets/download_widget.py
The list of scraped build is not being sorted when downloaded.
|  |  |  |  |  |  |  |  |  |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| NOT sorted | 4.x.x | 3.6.9 | 3.6.12 | 3.6.11 | 3.6.10 | ... |  3.3.9 | 3.3.1x |
| sorted | 4.x.x | 3.6.12 |  3.6.11 | 3.6.10 | 3.6.9 | ... | 3.3.1x | 3.3.9 |
Fix is just a 1 liner in the download widget.
I believe that just how they are listed and then get cough by the scraper.
I see the same "sort by first digit of patch number"  behaviour in the blender download pages [link](https://download.blender.org/release/Blender3.6/) .
---
https://github.com/Victor-IX/Blender-Launcher-V2/assets/21959185/b070f727-a061-4fe2-bdb0-7c1f17b1c51f 
https://github.com/Victor-IX/Blender-Launcher-V2/assets/21959185/9316bb0f-80cd-4569-a4b1-04d7708f29ce
=> fix: scraped list not sorted

source/modules/settings.py, source/threads/library_drawer.py, source/widgets/settings_window/general_tab.py, source/windows/main_window.py
This small change allows for directing the library folder to a point relative to the launcher's location. This is useful if, say, you save your builds to a USB to use them anywhere or move them to a different folder, you don't need to change your library folder in the launcher for it to function.
Another adjustment I would like to do: During first-time startup, detect if the folder is relative to the launcher's location. if so, ask if it should be relative.
Edit: Finished that second adjustment. Tell me what you think!
=> Allow relative library folders

source/widgets/base_page_widget.py
Feat #119 
Implemented toggling between ascending and descending sorting orders for datetime and version labels. Users can now switch sorting order.
=> Invert Columns Order

source/modules/build_info.py, source/threads/library_drawer.py, source/widgets/library_widget.py
Ideally the major features of BLV2 can be separated from the QT frontend. If that's accomplished, many parts of the launcher will not need to be loaded for certain aspects to still function. 
If you were to use Blender Launcher from the commandline to launch a certain build, all you will need is a list of builds and a method to launch them, no need to setup pool managers, scrape builds, etc.
(edit: I'm not sure why the fix i made before this pr was included in the history, but that's not part of this)
=> move launching logic outside of LibraryWidget

source/threads/scraper.py
As we have experienced, this may have given the *buttons* to download the Blender versions but if the user decided to actually click it, it was likely the downloaded file would be invalid. The downloaded file would just contain the error messages given from the scraping step.
Related to #130: The error is not clear and is caused by this bug
=> remove cache fallback

source/main.py, source/modules/_platform.py, source/modules/connection_manager.py, source/modules/settings.py, source/widgets/settings_window/connection_tab.py, source/windows/settings_window.py
Blender Foundation is currently blocking requests to [download.blender.org](https://download.blender.org/). 
I improved the header and included a User ID (UUID4), so they can better monitor the workload caused by the Blender Launcher per user and block users causing too many requests.
=> Connection header improvements 

source/main.py, source/modules/shortcut.py
This simplifies the Open-With function by removing the __launch_target  command and replacing it with a separate parser that runs before the default parser. this accomplishes the "launching a file" functionality without needing an unintuitive middleman.
Theoretically, if someone has a file named "launch", or "register", etc. next to the launcher they will cause false positives. in the script, This could be mediated by checking the suffix of the given path if we want to cover this edge case.
Edit: I have not tested it on windows.
=> Remove launch target

.github/workflows/release-winget.yml
Following issue https://github.com/Victor-IX/Blender-Launcher-V2/issues/141 Uses [winget-releaser](https://github.com/vedantmgoyal9/winget-releaser) I suggest you ( @Victor-IX) create a `Classic Github Token` with `public_repo` scope is created, following [this link](https://github.com/settings/tokens/new), then the Token can be added to the Blender-Launcher-V2 repo as a secret named `WINGET_ACC_TOKEN`. See below, that user also will have to fork the winget-pkgs repository.
Notes:
> You will need to create a *classic* Personal Access Token (PAT) with `public_repo` scope. New fine-grained PATs aren't supported by the action. Review #172 for information.
> Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. …
=>  Create Github Action to release winget package

source/modules/_resources_rc.py, source/modules/settings.py, source/windows/main_window.py
This lets the program continue after a failure of loading qt resources. In my opinion, it is better to just let the program load without the style data even if the program looks a little odd.
=> Replace Resources ImportError with Graphical Warning

.github/workflows/macos_release.yml, scripts/build_mac.sh
Prompted by https://github.com/Victor-IX/Blender-Launcher-V2/issues/153#issuecomment-2451078857
Very similar to the windows_release action.
A few notes:
- Until #160 is actioned, I've added a sed hack to expand the pyqt range to `>=`
- I've left building a dmg commented out (and deployed as zip) as it ballooned the size of the app to roughly 150MB, .zip is ~35MB.
Successful action run: https://github.com/illusional/Blender-Launcher-V2/actions/runs/11655072512/job/32449336187
Example of release: https://github.com/illusional/Blender-Launcher-V2/releases/tag/v2.2.99999999
Let me know what you think @Victor-IX / @zeptofine!
=> Add build action for MacOS 

source/threads/scraper.py
Prompted by: https://github.com/Victor-IX/Blender-Launcher-V2/issues/153#issuecomment-2453104799
Suggested by @xx88xx
@Victor-IX, how does Windows do this for the "stable" build side, I saw your PR #106 is targeted at "automated" releases.
This is just a suggestion of my very limited knowledge of the codebase, happy to move this code to somewhere more sensible. I've added code for x86, but there aren't many GH runners that run macos on intel - mostly if someone wanted to build it for themselves.
=> Filter stable mac builds to current architecture

run.ps1, scripts/update_cache_api.py, source/main.py, source/resources/api/stable_builds_api_linux.json, source/resources/api/stable_builds_api_macos.json, source/resources/api/stable_builds_api_windows.json, source/threads/scraper.py, source/windows/main_window.py
Add a new arg to force cache all builds for all platforms and add a script to update the corresponding API files
In the future, this will be run every week by a GitHub action to save new blender releases in the API cache
=> Build caching automation

source/modules/settings.py, source/widgets/settings_window/appearance_tab.py, source/windows/main_window.py
- Add missing tabs in the default tab and page option dropdown
- Remove sync tab settings as this doesn't make sense to have it anymore as the tabs are not the same between lib and download 
#188
=> Settings fix

source/widgets/onboarding_setup/wizard_pages.py
By checking if the binary is under the user folder (ex. `/home/user`), we can make a pretty good guess on whether the binary has the permissions to move itself to the library. If the binary is outside the user folder, we disable the `Move exe` feature by default, and add a warning (but the user can still decide to enable this feature).
This is mainly for packaging efforts like the AUR, where Blender Launcher is usually installed somewhere like `/usr/bin` or `/bin`, and thus cannot move itself anyway.
=> fix: Check if binary is outside the user folder for `Move exe`

source/widgets/onboarding_setup/wizard_pages.py
Fix the typo present in the onboarding window.
=> Fix 'permisisons' typo in onboarding

source/widgets/library_widget.py
Due to a bug/feature in Pyinstaller, `xdg-open` won't work properly by default. This is due to Pyinstaller changing environment variables at runtime, breaking what `xdg-open` expects.
As a workaround, before running `xdg-open`, we create a copy of the environment variables, and remove any variable (except `PATH`) that contains `tmp` (as noted in
https://github.com/pyinstaller/pyinstaller/issues/3668#issuecomment-742547785). We then pass that modified copy to `subprocess.run` (thus leaving the original environment variables unmodified for the rest of Blender Launcher).
=> fix: Fix issues with `xdg-open` when built with Pyinstaller

source/modules/shortcut.py, source/widgets/library_widget.py, source/widgets/onboarding_setup/wizard_pages.py, source/widgets/settings_window/general_tab.py
As per #233.
- When clicking "Create Shortcut", a location for the shortcut can be specified, defaulting to the XDG folder for .desktop files (```~/.local/share/applications```), and ```Start Menu/Programs``` on Windows, in line with where the Blender Launcher shortcut is put.
- Split ```get_default_shortcut_destination``` into 3 methods, to make it more usable for sharing between Blender Launcher- and Blender shortcuts.
- Small typo in the first-run wizard.
=> Linux - Use XDG path for .desktop files

docs/mkdocs/development.md, docs/mkdocs/settings.md, source/main.py
1. Fix required Python version in the documentation. Unrelated to theme of this PR, just a small fix.
2. Add command line arguments to the documentation
3. Mention `launch --help` and `update --help` in their description to make them more descriable as it's easy to confuse them with just positional arguments that don't have their own suboptions.
=> Command line arguments documentation

source/main.py
Found an issue with the commit submitted by me before (2e3c191), it's skipping all `--` arguments though it's still possible to provide additional Blender arguments. 
E.g. it's possible to launch  blender with something like `blender --factory-startup --background --python-expr "import sys; print(sys.argv") -- argv1 argv2` and the output will be similar to:
```
['L:/Projects/Github/Blender-Launcher-V2/downloads/stable/blender-4.4.3-stable.802179c51ccc/blender.exe', '--factory-startup', '--background', '--python-expr', 'import sys; print(sys.argv)', '--', 'argv1', 'argv2']
```
But without this fix, `--` will be skipped leading to incorrect results.
=> Support double dash Blender argument

source/modules/version_matcher.py
`commit_time` is no longer `None` by default, so set it back to "*" for tests
=> Fix test after c28f5a7

Makefile, docs/mkdocs/development.md, pyproject.toml, source/modules/version_matcher.py
Changes:
- support running pytest for rich assert messages
- Add simple makefile for running Blender Launcher and starting tests (perhaps there will be more in the future)
=> Support pytest and add simple makefile
